fcm:
  path: albaayo-c08d1-firebase-adminsdk-7hkp4-f330c3d2c8.json
  androidTestToken: cYPgfcNARAaizWM6DnNbue:APA91bFbxqTaYpD_7m1CO4R7wv4mMy96w3E5M6h9qw0fJYh97uF81sIgzTyYHW1p4N4eFR47lwzj2_8SA2yGscYOzOuVFoLpfXaJrkrm79xmUMY66UeGgG6YzSLCQqHq2cqvp9BfOp4i